/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as CartRouteImport } from './routes/cart'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrdersOrderIdRouteImport } from './routes/orders.$orderId'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AiResearchRouteImport } from './routes/ai.research'
import { Route as AiEmailRouteImport } from './routes/ai.email'
import { Route as AiChatbotRouteImport } from './routes/ai.chatbot'

const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => OrdersRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AiResearchRoute = AiResearchRouteImport.update({
  id: '/ai/research',
  path: '/ai/research',
  getParentRoute: () => rootRouteImport,
} as any)
const AiEmailRoute = AiEmailRouteImport.update({
  id: '/ai/email',
  path: '/ai/email',
  getParentRoute: () => rootRouteImport,
} as any)
const AiChatbotRoute = AiChatbotRouteImport.update({
  id: '/ai/chatbot',
  path: '/ai/chatbot',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/menu': typeof MenuRoute
  '/orders': typeof OrdersRouteWithChildren
  '/ai/chatbot': typeof AiChatbotRoute
  '/ai/email': typeof AiEmailRoute
  '/ai/research': typeof AiResearchRoute
  '/api/chat': typeof ApiChatRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/menu': typeof MenuRoute
  '/orders': typeof OrdersRouteWithChildren
  '/ai/chatbot': typeof AiChatbotRoute
  '/ai/email': typeof AiEmailRoute
  '/ai/research': typeof AiResearchRoute
  '/api/chat': typeof ApiChatRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/menu': typeof MenuRoute
  '/orders': typeof OrdersRouteWithChildren
  '/ai/chatbot': typeof AiChatbotRoute
  '/ai/email': typeof AiEmailRoute
  '/ai/research': typeof AiResearchRoute
  '/api/chat': typeof ApiChatRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/menu'
    | '/orders'
    | '/ai/chatbot'
    | '/ai/email'
    | '/ai/research'
    | '/api/chat'
    | '/orders/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/menu'
    | '/orders'
    | '/ai/chatbot'
    | '/ai/email'
    | '/ai/research'
    | '/api/chat'
    | '/orders/$orderId'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/menu'
    | '/orders'
    | '/ai/chatbot'
    | '/ai/email'
    | '/ai/research'
    | '/api/chat'
    | '/orders/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  MenuRoute: typeof MenuRoute
  OrdersRoute: typeof OrdersRouteWithChildren
  AiChatbotRoute: typeof AiChatbotRoute
  AiEmailRoute: typeof AiEmailRoute
  AiResearchRoute: typeof AiResearchRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof OrdersRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai/research': {
      id: '/ai/research'
      path: '/ai/research'
      fullPath: '/ai/research'
      preLoaderRoute: typeof AiResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai/email': {
      id: '/ai/email'
      path: '/ai/email'
      fullPath: '/ai/email'
      preLoaderRoute: typeof AiEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai/chatbot': {
      id: '/ai/chatbot'
      path: '/ai/chatbot'
      fullPath: '/ai/chatbot'
      preLoaderRoute: typeof AiChatbotRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface OrdersRouteChildren {
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
}

const OrdersRouteChildren: OrdersRouteChildren = {
  OrdersOrderIdRoute: OrdersOrderIdRoute,
}

const OrdersRouteWithChildren =
  OrdersRoute._addFileChildren(OrdersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  MenuRoute: MenuRoute,
  OrdersRoute: OrdersRouteWithChildren,
  AiChatbotRoute: AiChatbotRoute,
  AiEmailRoute: AiEmailRoute,
  AiResearchRoute: AiResearchRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
